#include "malloc.h"
#include <stdio.h>
#include <stdint.h>
#include <limits.h>

t_allocator		g_alloc = {
	.tiny = NULL,
	.small = NULL,
	.large = NULL,
	// .mutex = PTHREAD_MUTEX_INITIALIZER,
	.env.MALLOC_LOG_ = false,
	.env.MALLOC_MMAP_MAX_ENABLE_ = false,
	.env.MALLOC_PERTURB_ENABLE_ = false,
	.env.MALLOC_MMAP_THRESHOLD_ENABLE_ = false,
	.env.mmap_max = 0,
	.counter.mmap_total = 0,
	.counter.split_number = 0,
	.counter.merge_number = 0
};

static bool	is_space(char c)
{
	return (c == ' ' || (c >= 9 && c <= 13));
}

static bool	parse_u10_strict(const char *value, unsigned long *out)
{
	const char		*p = value;
	unsigned long	result = 0;
	int				digit;

	if (!value || !out)
		return false;
	while (is_space(*p))
		p++;
	if (*p == '+')
		p++;
	else if (*p == '-')
		return false;
	if (*p < '0' || *p > '9')
		return false;
	while (*p >= '0' && *p <= '9') {
		digit = *p - '0';
		if (result > (ULONG_MAX - (unsigned long)digit) / 10UL)
			return false;
		// result = result 10UL + (unsigned long)digit;
		p++;
	}
	if (*p != '\0')
		return false;
	*out = result;
	return true;
}

// Parse an env var once and expose both:
// - enabled: true only for a full numeric value different from "0"
// - value: parsed numeric value, otherwise 0
// static t_env_value	read_env_value(const char *name) {
// 	t_env_value	out;
// 	char	*value = getenv(name);
// 	unsigned long	parsed;

// 	out.enabled = false;
// 	out.value = 0;

// 	if (!value || !*value)
// 		return out;
// 	if (value[0] == '0' && value[1] == '\0')
// 		return out;
// 	if (parse_u10_strict(value, &parsed) && parsed > 0) {
// 		out.value = (size_t)parsed;
// 		out.enabled = true;
// 	}
// 	return out;
// }


// Fills the user area with pseudo-random bytes.
// If inverted is true, each generated byte is bitwise inverted (used on free).
void	perturb_fill(void *ptr, size_t len, bool inverted)
{
	unsigned char	*p = (unsigned char *)ptr;
	unsigned char	seed = (g_alloc.env.MALLOC_PERTURB_VALUE_ & 0xFF);
	u32_t			state = ((u32_t)(uintptr_t)ptr) ^ ((u32_t)len << 1) ^ ((u32_t)seed << 24) ^ 0x9E3779B9u;
	size_t			i = 0;
	unsigned char	byte;

	if (state == 0)
		state = 0xA5A5A5A5u;
	while (i < len) {
		state ^= state << 13;
		state ^= state >> 17;
		state ^= state << 5;
		byte = (unsigned char)(state & 0xFF);
		if (inverted)
			byte = (unsigned char)~byte;
		p[i++] = byte;
	}
}

// Allocate the zone and create the first block with all rest memory and initialize it.
static t_zone	*create_zone(size_t zone_size, e_block_kind kind)
{
	t_zone	*zone ;/*= mmap(0, zone_size, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
	if (zone == MAP_FAILED)
		return NULL;*/

	zone->zone_size		= zone_size;
	zone->free_blocks	= 1;
	zone->total_blocks	= 1;
	zone->next			= NULL;

	t_block	*block = (t_block *)(zone + 1);
	block->size		= zone_size - sizeof(t_zone) - sizeof(t_block);
	block->is_free	= true;
	block->next		= NULL;
	block->prev		= NULL;
	block->kind		= kind;
	block->owner	= zone;

	zone->block_list = block;
	g_alloc.counter.mmap_total++;
	return zone;
}


// Splits a block into two blocks if there is enough remaining space.
//
// Before split :
//
//  block
//   |
//   v
//  [ t_block | . . . . . . . data (block->size bytes) . . . . . . . ]
//
// After split :
//
//  block                        new_block
//   |                                |
//   v                                v
//  [ t_block | data (align_mem) | t_block | data (remaining bytes) ]
//              ^                  ^
//              |                  (char *)(block + 1) + align_mem
//              user gets this ptr = (void *)(block + 1)
//
// The split only occurs if the remaining space after align_mem is large
// enough to hold a t_block header plus at least ALIGN8(1) bytes of data.
// new_block is inserted right after block in the free list.
//
// Returns true if the split was performed, false otherwise.
bool	split_block(t_block *block, size_t align_mem)
{
	t_block	*new_block;

	if (block->size < align_mem + sizeof(t_block) + ALIGN8(1))
		return false;

	new_block			= (t_block *)((char *)(block + 1) + align_mem);
	new_block->is_free	= true;
	new_block->next		= block->next;
	new_block->prev		= block;
	new_block->size		= block->size - align_mem - sizeof(t_block);
	new_block->owner	= block->owner;
	new_block->kind		= block->kind;

	if (block->next)
		block->next->prev = new_block;
	block->next = new_block;
	block->size = align_mem;
	g_alloc.counter.split_number++;
	return true;
}

// Create TINY or SMALL type zone
static void	*allocate_block(size_t align_mem, size_t zone_size,
						e_block_kind kind, t_zone **zone_head)
{
	t_zone	*zone = NULL;
	t_block	*block = NULL;
	bool	did_split = false;

	if (!*zone_head) {
		*zone_head = create_zone(zone_size, kind);
		if (!*zone_head) {
			if (g_alloc.env.MALLOC_LOG_)
				printf(BLD_RED"Error: mmap() failed at %s zone creation"RESET, kind == TINY ? "TINY" : "SMALL");
			return NULL;
		}
	}

	zone = *zone_head;
	while (zone) {
		if (zone->free_blocks > 0) {
			block = zone->block_list;
			while (block && (!block->is_free || block->size < align_mem))
				block = block->next;
			if (block)
				break;
		}
		zone = zone->next;
	}
	if (!block) {
		zone = create_zone(zone_size, kind);
		if (!zone) {
			if (g_alloc.env.MALLOC_LOG_)
				printf(BLD_RED"Error: mmap() failed at %s zone creation"RESET, kind == TINY ? "TINY" : "SMALL" );
			return NULL;
		}
		zone->next = *zone_head;
		*zone_head = zone;
		block = zone->block_list;
	}
	did_split = split_block(block, align_mem);
	if (did_split)
		zone->total_blocks++;
	else
		zone->free_blocks--;
	block->is_free = false;
	if (g_alloc.env.MALLOC_PERTURB_ENABLE_ && g_alloc.env.MALLOC_PERTURB_VALUE_)
		perturb_fill((void *)(block + 1), block->size, false);
	return (void *)(block + 1);
}

// Create specific LARGE type zone
static void	*large(size_t zone_large_size, t_zone **zone_head)
{
	t_zone	*zone;
	t_block	*block;
	bool can_mmap = true;

	if (g_alloc.env.MALLOC_MMAP_MAX_ENABLE_)
		can_mmap = (g_alloc.env.mmap_max < g_alloc.env.MALLOC_MMAP_MAX_VALUE_);

	if(can_mmap) {
		zone = create_zone(zone_large_size, LARGE);
		if (!zone) {
			if (g_alloc.env.MALLOC_LOG_)
				printf(BLD_RED"Error: mmap() failed at LARGE zone creation"RESET);
			return NULL;
		}
	}
	else if(g_alloc.env.MALLOC_LOG_) {
		printf(BLD_RED"Error: MALLOC_MMAP_MAX_ (%lu) reached\n"RESET, g_alloc.env.MALLOC_MMAP_MAX_VALUE_);
		return NULL;
	}
	else
		return NULL;
	block = zone->block_list;
	block->is_free = false;
	zone->free_blocks = 0;
	zone->total_blocks = 1;
	zone->next = *zone_head;
	*zone_head = zone;
	if (g_alloc.env.MALLOC_PERTURB_ENABLE_ && g_alloc.env.MALLOC_PERTURB_VALUE_)
		perturb_fill((void *)(block + 1), block->size, false);
	g_alloc.env.mmap_max++;
	return (void *)(block + 1);
}

// void	is_env_var()
// {
// 	t_env_value	v;

// 	v = read_env_value("MALLOC_LOG_");
// 	g_alloc.env.MALLOC_LOG_ = v.enabled;

// 	v = read_env_value("MALLOC_MMAP_MAX_");
// 	g_alloc.env.MALLOC_MMAP_MAX_VALUE_ = v.value;
// 	g_alloc.env.MALLOC_MMAP_MAX_ENABLE_ = v.enabled;

// 	v = read_env_value("MALLOC_MMAP_THRESHOLD_");
// 	g_alloc.env.MALLOC_MMAP_THRESHOLD_VALUE_ = v.value;
// 	g_alloc.env.MALLOC_MMAP_THRESHOLD_ENABLE_ = v.enabled;

// 	v = read_env_value("MALLOC_PERTURB_");
// 	g_alloc.env.MALLOC_PERTURB_VALUE_ = v.value;
// 	g_alloc.env.MALLOC_PERTURB_ENABLE_ = v.enabled;
// }

void	*internal_malloc(size_t size)
{
	if (size <= (size_t)0)
		return NULL;

	size_t	align_mem = ALIGN8(size);

	if (g_alloc.env.MALLOC_MMAP_THRESHOLD_ENABLE_ && align_mem >= g_alloc.env.MALLOC_MMAP_THRESHOLD_VALUE_)
		return large(LARGE_ZONE_SIZE(size), &g_alloc.large);

	if (align_mem <= TINY_MAX)
		return allocate_block(align_mem, TINY_ZONE_SIZE, TINY, &g_alloc.tiny);
	else if (align_mem <= SMALL_MAX)
		return allocate_block(align_mem, SMALL_ZONE_SIZE, SMALL, &g_alloc.small);
	else
		return large(LARGE_ZONE_SIZE(size), &g_alloc.large);

	return NULL;
}

void	*malloc(size_t size)
{
	void *ptr;

	// pthread_mutex_lock(&g_alloc.mutex);
	is_env_var();
	ptr = internal_malloc(size);
	// pthread_mutex_unlock(&g_alloc.mutex);

	return ptr;
}